# Makefile Comment
#
# Driver Makefile
#
# Honor Pledge:
#
# I pledge that I have neither given nor
# received any help on this assignment.
#
# Jonathan Wang

Race.exe: driver.o car.o
	g++ driver.o car.o -o Race.exe
	
driver.o: driver.cpp
	g++ -c driver.cpp -o driver.o
	
car.o: car.cpp
	g++ -c car.cpp -o car.o
	
clean:
	rm *.o Race.exe
	
run:
	Race.exe
